spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    user: root
    password: 123
  datasource:
    url: jdbc:postgresql://localhost:5432/task2
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_fetch_size: 20
        format_sql: true
        jdbc:
          batch_size: 20


